### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent Error

### ISSUE THREAD

**Issue by lolo773** [Cowings/Echo#1]
Error with strike citizens bots.

`[14:40:22] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to Echo vgit-Echo-d96b491
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot.jar:git-TacoSpigot-bf023c7d]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[spigot.jar:git-TacoSpigot-bf023c7d]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-TacoSpigot-bf023c7d]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:508) [spigot.jar:git-TacoSpigot-bf023c7d]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:493) [spigot.jar:git-TacoSpigot-bf023c7d]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:91) [spigot.jar:git-TacoSpigot-bf023c7d]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:577) [spigot.jar:git-TacoSpigot-bf023c7d]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:490) [spigot.jar:git-TacoSpigot-bf023c7d]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:609) [spigot.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1157) [spigot.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.EntityHuman.d(EntityHuman.java:868) [spigot.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:787) [spigot.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:809) [spigot.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:507) [spigot.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1010) [spigot.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1089) [spigot.jar:git-TacoSpigot-bf023c7d]
	at net.citizensnpcs.nms.v1_8_R3.util.NMSImpl.attack(NMSImpl.java:210) [Citizens.jar:?]
	at net.citizensnpcs.util.NMS.attack(NMS.java:56) [Citizens.jar:?]
	at net.citizensnpcs.npc.ai.MCTargetStrategy$1.handle(MCTargetStrategy.java:270) [Citizens.jar:?]
	at net.citizensnpcs.npc.ai.MCTargetStrategy.update(MCTargetStrategy.java:133) [Citizens.jar:?]
	at net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:163) [Citizens.jar:?]
	at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:358) [Citizens.jar:?]
	at net.citizensnpcs.nms.v1_8_R3.entity.EntityHumanNPC.t_(EntityHumanNPC.java:399) [Citizens.jar:?]
	at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1719) [spigot.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.World.g(World.java:1688) [spigot.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1519) [spigot.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:603) [spigot.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:853) [spigot.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:410) [spigot.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:720) [spigot.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:623) [spigot.jar:git-TacoSpigot-bf023c7d]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.NullPointerException
	at ac.echo.listeners.FreezeListener.onDamage(FreezeListener.java:53) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:307) ~[spigot.jar:git-TacoSpigot-bf023c7d]
	... 31 more
`

**Comment by Cowings** [comment]
I'll look into this tomorrow. This seems like an issue with not being able to cast citizens bots as players/profiles.
Will be pushing out an update soon.

**Comment by Cowings** [comment]
Issued fixed in release 1.14/70e43fe.
https://github.com/Cowings/Echo/releases/tag/1.14
